http:
  routers:
    backend-router:
      rule: "Host(`api.debyez.localhost`)"
      entryPoints:
        - "web"
      service: "backend-service"

    frontend-router:
      rule: "Host(`app.debyez.localhost`)"
      entryPoints:
        - "web"
      service: "frontend-service"

  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://backend:8000"

    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend:80"